version: '3.8'

services:
  fastapi_ylab:
    container_name: fastapi_ylab
    build:
      context: /
      dockerfile: app/Dockerfile
    environment:
      DATABASE_URL: "postgres_y_lab/postgres"
    entrypoint: sh -c "poetry run python main.py"
    networks:
      - y_lab_network
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://fastapi_ylab:8000/health || exit 1
      interval: 15s
      retries: 20
      start_period: 10s
      timeout: 10s
    depends_on:
      postgres_y_lab:
        condition: service_healthy

  postgres_y_lab:
    container_name: postgres_y_lab
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGUSER: "postgres"
    expose:
      - 5432
    networks:
      - y_lab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  redis:
    image: "redis:7.2-rc3-alpine"
    container_name: y_lab_redis
    networks:
      - y_lab_network

networks:
  y_lab_network:
    name: y_lab_network
volumes:
  postgres_data:
